#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "DIR: $DIR"
echo "-----------------------------------------------------"
#Copy this file to defaults.sh
#DO NOT EDIT THIS FILE, BUT EDIT DEFAULTS.SH INSTEAD

##############################################################
######################### EDIT THESE #########################
##############################################################

## Full User Name for GIT
export INST_GIT_FULL_NAME='Andries Jongsma'

## E-mail address for GIT
export INST_GIT_EMAIL='a.jongsma@gmail.com'

#-----------------------------------------------------------

#Specify your SED binary
export SED="/usr/local/bin/gsed"

#-----------------------------------------------------------

## Apache
export INST_APACHE_SYSTEM_WEB_ROOT='/Library/WebServer/Documents/'

#-----------------------------------------------------------

## NewzNAB
export INST_NEWZNAB_PATH="/Users/Newznab/Sites/newznab"
export INST_NEWZNAB_SVN_UID='svnplus'
export INST_NEWZNAB_SVN_PW='svnplu5'
export INST_NEWZNAB_MYSQL_UID="newznab"
export INST_NEWZNAB_MYSQL_PW="mini_newznab"

#-----------------------------------------------------------

## News Server Provider
export INST_NEWSSERVER_SERVER='reader.xsnews.nl'
export INST_NEWSSERVER_SERVER_UID='105764'
export INST_NEWSSERVER_SERVER_PW=''
export INST_NEWSSERVER_SERVER_PORT_SSL='563'

############################################################

## By using this script you understand that the programmer is not responsible for any loss of data, users, or sanity.
## You also agree that you were smart enough to make a backup of your database and files. Do you agree? yes/no
export AGREED="yes"

##END OF EDITS##



############################################################
############################################################

##Should not need to change
export INST_NEWZNAB_UPDATE_PATH=$NEWZNAB_PATH"/misc/update_scripts"
export INST_NEWZNAB_TESTING_PATH=$NEWZNAB_PATH"/misc/testing"
export INST_NEWZNAB_ADMIN_PATH=$NEWZNAB_PATH"/www/admin"

############################################################
