## PATH
# X11
PATH=$PATH:/usr/X11/bin
# homebrew
PATH=/usr/local/bin:/usr/local/sbin:$PATH
# GNU coreutils
PATH=/opt/local/libexec/gnubin/:$PATH

#PS1="$PS1"'$([ -n "$TMUX" ] && tmux setenv TMUXPWD_$(tmux display -p "#D" | tr -d %) "$PWD")'